Initial commit HW34
jetyyya/javaAQA pull request #14
Opened 2023-07-01 16:43 UTC by jetyyya

Added: Homework for lesson 34

2023-07-03 15:38 UTC, Bibi4kovIgor requested changes

2023-07-03 15:38 UTC, Bibi4kovIgor commented on HW34/.gitignore
> +### IntelliJ IDEA ###
It is not needed to store all of configs in .gitignore file, that there are not used

2023-07-03 15:38 UTC, Bibi4kovIgor commented on HW34/.gitignore
> +### Eclipse ###
It is not needed to store all of configs in .gitignore file, that there are not used

2023-07-03 15:38 UTC, Bibi4kovIgor commented on HW34/.gitignore
> +### NetBeans ###
It is not needed to store all of configs in .gitignore file, that there are not used

2023-07-03 15:38 UTC, Bibi4kovIgor commented on HW34/.gitignore
> +.vscode/
It is not needed to store all of configs in .gitignore file, that there are not used

2023-07-08 09:44 UTC, jetyyya commented on HW34/.gitignore
> +### IntelliJ IDEA ###
учту на майбутнє

2023-07-13 22:00 UTC, Bibi4kovIgor approved these changes

2023-07-13 22:00 UTC, merged