Initial commit HW25
jetyyya/javaAQA pull request #9
Opened 2023-05-28 13:27 UTC by jetyyya

Added: Homework for lesson 25

2023-06-10 00:31 UTC, Bibi4kovIgor requested changes

2023-06-10 00:31 UTC, Bibi4kovIgor commented on HW26/src/main/java/com/alevel/operators/HW26GameOfTheCity.java
> +                    lastLetter = Character.toUpperCase(city.charAt(city.length() - 1));
Вище вже ініціалізовано дану змінну ідентичними параметрами.
Навіщо дублювати виклик функції? Чи не краще перевикористати змінну, яка була раніше проініціалізована?

2023-06-10 00:31 UTC, Bibi4kovIgor commented on HW26/src/main/java/com/alevel/operators/HW26GameOfTheCity.java
> +                    foundCity = true;
Замість використання прапору всередині алгоритму, краще цей метод  розбити на 2 окремі методи

2023-06-10 00:31 UTC, Bibi4kovIgor commented on HW26/src/main/java/com/alevel/operators/HW26GameOfTheCity.java
> +            if (!foundCity) {
Див. коментар вище

2023-06-10 00:31 UTC, Bibi4kovIgor commented on HW26/src/main/java/com/alevel/operators/HW26GameOfTheCity.java
> +            if (playerCity.equalsIgnoreCase("exit")) {
Краще дану умову перенести до умови циклу while, що розташований вище

2023-06-10 00:31 UTC, Bibi4kovIgor commented on HW26/src/main/java/com/alevel/operators/HW26GameOfTheCity.java
> +            if (firstLetter != lastLetter) {
Краще всі умови завершення циклу прописати у циклі while, що розміщений вище

2023-06-10 00:31 UTC, Bibi4kovIgor commented on HW26/src/main/java/com/alevel/operators/HW26GameOfTheCity.java
> +    }
Краще, виділити із даного циклу окремі методи

2023-06-10 11:05 UTC, jetyyya commented on HW26/src/main/java/com/alevel/operators/HW26GameOfTheCity.java
> +                    lastLetter = Character.toUpperCase(city.charAt(city.length() - 1));
Мені здавалось, що для циклу треба окрему змінну, для наочності - виправлю

2023-06-10 11:06 UTC, jetyyya commented on HW26/src/main/java/com/alevel/operators/HW26GameOfTheCity.java
> +                    foundCity = true;
Ми тоді ще не розмовляли про модульність, але так прапори зло :)

2023-06-10 11:06 UTC, jetyyya commented on HW26/src/main/java/com/alevel/operators/HW26GameOfTheCity.java
> +            if (!foundCity) {
+

2023-06-10 11:06 UTC, jetyyya commented on HW26/src/main/java/com/alevel/operators/HW26GameOfTheCity.java
> +            if (playerCity.equalsIgnoreCase("exit")) {
не зрозумів, усі умови у мене у циклі while... вони брейкають цикл, як вони можуть бути не в ньому?

2023-06-10 11:06 UTC, jetyyya commented on HW26/src/main/java/com/alevel/operators/HW26GameOfTheCity.java
> +            if (firstLetter != lastLetter) {
не зрозумів, усі умови у мене у циклі while... вони брейкають цикл, як вони можуть бути не в ньому?

2023-06-10 11:07 UTC, jetyyya commented on HW26/src/main/java/com/alevel/operators/HW26GameOfTheCity.java
> +    }
щаз перероблю...

2023-06-17 12:42 UTC, merged

2023-06-22 16:03 UTC, Bibi4kovIgor reviewed
Виправ, пліз всі зауваження та відміть як "resolved"

2023-06-22 16:03 UTC, Bibi4kovIgor commented on HW26/src/main/java/com/alevel/operators/HW26GameOfTheCity.java
> +        char lastLetter = Character.toUpperCase(lastCity.charAt(lastCity.length() - 1));
Краще тут скористатися стандартними функціями String

2023-06-22 16:03 UTC, Bibi4kovIgor commented on HW26/src/main/java/com/alevel/operators/HW26GameOfTheCity.java
> +        while (true) {
gameplay краще винести в окремий метод